spring:
  application:
    name: Incident-Consumer

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  Kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: incident-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest

      properties:
        "[spring.json.value.default.type]": "com.Tatertot.Incident_Consumer.event.IncidentEvent"
        "[spring.json.trusted.packages]": "com.Tatertot.Incident_Consumer.event"
        "[spring.json.use.type.headers]": false

    listener:
      concurrency: 3
      ack-mode: record

app:
  Kafka:
    incident-topic: incident-events